//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionTableCreator.Templates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DecisionTableCreator.Templates.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delimiters &quot;$&quot;, &quot;$&quot;
        ///
        ///TestCasesRoot(root) ::= &lt;&lt;
        ///&lt;!DOCTYPE&gt;
        ///&lt;HTML&gt;
        ///&lt;BODY&gt;
        ///&lt;TABLE border=&quot;1&quot; cellpadding=&quot;2&quot; cellspacing=&quot;0&quot;&gt;
        ///	&lt;TR&gt;
        ///		&lt;TD bgcolor=&quot;White&quot;&gt;&amp;nbsp&lt;/TD&gt;
        ///$root.TestCases:TestCase(); separator=&quot;\r\n&quot;$
        ///	&lt;/TR&gt;
        ///	&lt;TR&gt;
        ///		&lt;TD bgcolor=&quot;DarkGray&quot;&gt;&lt;i&gt;&lt;strong&gt;Conditions&lt;/strong&gt;&lt;/i&gt;&lt;/TD&gt;
        ///$root.TestCases:TestCaseDummy(); separator=&quot;\r\n&quot;$
        ///	&lt;/TR&gt;
        ///$root.Conditions:ConditionOrAction(); separator=&quot;\r\n&quot;$
        ///	&lt;TR&gt;
        ///		&lt;TD bgcolor=&quot;DarkGray&quot;&gt;&lt;i&gt;&lt;strong&gt;Actions&lt;/strong&gt;&lt;/i&gt;&lt;/TD&gt;
        ///$root.TestCases:TestCaseD [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HtmlTemplate {
            get {
                return ResourceManager.GetString("HtmlTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RtfTemplate {
            get {
                return ResourceManager.GetString("RtfTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///TestCasesRoot(root) ::= &lt;&lt;
        ///conditions count == &lt;root.Conditions.Count&gt;
        ///List conditions
        ///&lt;root.Conditions:ConditionOrAction(); separator=&quot;\r\n&quot;&gt;
        ///
        ///actions count == &lt;root.Actions.Count&gt;
        ///List actions:
        ///&lt;root.Actions:ConditionOrAction(); separator=&quot;\r\n&quot;&gt;
        ///
        ///test cases count == &lt;root.TestCases.Count&gt;
        ///List test cases:
        ///&lt;root.TestCases:TestCase();separator=&quot;\r\n&quot;&gt;
        ///&gt;&gt;
        ///
        ///ConditionOrAction(co) ::= &lt;&lt;	&lt;co.Name&gt;
        ///		Possible Values:
        ///			enum value count &lt;co.EnumValues.Count&gt;
        ///&lt;co.EnumValues:EnumValue(); separa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Sample_file {
            get {
                return ResourceManager.GetString("Sample_file", resourceCulture);
            }
        }
    }
}
