using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using DecisionTableCreator.DynamicTable;
using DecisionTableCreator.TestCases;
using DecisionTableCreator.Utils;
using Microsoft.Win32;

namespace DecisionTableCreator
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }

        DataContainer DataContainer { get { return (DataContainer)DataContext; } }

        private void DataGrid_OnAutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            DataGrid dataGrid = sender as DataGrid;
            DataGridTextColumn col = e.Column as DataGridTextColumn;

            //// exchange DataGridTextColumn with DataGridTemplateColumn and GridCellControl

            DataGridHeader header = new DataGridHeader(col.Header.ToString(), dataGrid.Columns.Count);

            DataGridTemplateColumn templateColumn = new DataGridTemplateColumn();
            templateColumn.Header = header;

            Binding bind = new Binding(col.Header.ToString());
            bind.Mode = BindingMode.TwoWay;

            FrameworkElementFactory gridCellControl = new FrameworkElementFactory(typeof(GridCellControl));
            gridCellControl.SetBinding(DataContextProperty, bind);
            DataTemplate dataTemplate = new DataTemplate();
            dataTemplate.VisualTree = gridCellControl;

            templateColumn.CellTemplate = dataTemplate;

            e.Column = templateColumn;
        }

        private void DataGrid_OnAutoGeneratedColumns(object sender, EventArgs e)
        {
            DataGrid dataGrid = (DataGrid)sender;
            for (int idx = 0; idx < dataGrid.Columns.Count; idx++)
            {
                DataGridColumn col = dataGrid.Columns[idx] as DataGridColumn;

                // add sync column width
                AddToDictionary(dataGrid, col);
                var widthPropertyDescriptor = DependencyPropertyDescriptor.FromProperty(DataGridColumn.WidthProperty, typeof(DataGridColumn));
                widthPropertyDescriptor.AddValueChanged(col, ValueChangedHandler);
            }
        }


        #region SyncColumnWidth

        // dictionary for sync column width
        Dictionary<string, List<DataGridColumnContainer>> ColumnsWidthSyncDictionary = new Dictionary<string, List<DataGridColumnContainer>>();


        void AddToDictionary(DataGrid dataGrid, DataGridColumn col)
        {
            DataGridColumnContainer container = new DataGridColumnContainer(dataGrid, col);

            string key = GetColumnKey(container.Column.Header.ToString());
            if (ColumnsWidthSyncDictionary.ContainsKey(key))
            {
                var result = ColumnsWidthSyncDictionary[key].Where(cc => cc.DataGrid.Equals(dataGrid)).ToArray();
                foreach (DataGridColumnContainer cont in result)
                {
                    ColumnsWidthSyncDictionary[key].Remove(cont);
                }
                ColumnsWidthSyncDictionary[key].Add(container);
            }
            else
            {
                List<DataGridColumnContainer> colContainer = new List<DataGridColumnContainer>();
                ColumnsWidthSyncDictionary.Add(key, colContainer);
                colContainer.Add(container);
            }

        }

        string GetColumnKey(string name)
        {
            if (name.Contains("Action") || name.Contains("Condition"))
            {
                return "ConditionOrAction";
            }
            return name;
        }

        private void ValueChangedHandler(object sender, EventArgs eventArgs)
        {
            DataGridColumn col = sender as DataGridColumn;
            DataGridLength value = col.Width;
            foreach (DataGridColumnContainer column in ColumnsWidthSyncDictionary[GetColumnKey(col.Header.ToString())])
            {
                if (!col.Equals(column.Column))
                {
                    column.Column.Width = value;
                }
            }

        }

        #endregion

        private void AppendTestCase_OnCanExecute(object sender, CanExecuteRoutedEventArgs e)
        {
            e.CanExecute = true;
        }

        private void AppendTestCase_Executed(object sender, ExecutedRoutedEventArgs e)
        {
            var tcr = DataContainer.TestCasesRoot;
            tcr.AppendTestCase();
        }

        private void InsertTestCase_Executed(object sender, ExecutedRoutedEventArgs e)
        {
            var tcr = DataContainer.TestCasesRoot;
            int index = CalculateColumnIndex(e, true);
            tcr.InsertTestCase(index);
        }

        private void InsertTestCase_OnCanExecute(object sender, CanExecuteRoutedEventArgs e)
        {
            int index = CalculateColumnIndex(e, true);
            // focus must be at least on first testcase
            if (index >= 1)
            {
                e.CanExecute = true;
            }
        }


        private void EditCondition_Executed(object sender, ExecutedRoutedEventArgs e)
        {
            var index = CalculateRowIndex(e);
            if (index >= 0)
            {
                ConditionObject original = ((ConditionObject)DataContainer.TestCasesRoot.Conditions[index]);
                ConditionObject coClone = original.Clone();
                EditCondition wnd = new EditCondition(coClone);
                bool? result = wnd.ShowDialog();
                if (result.HasValue && result.Value)
                {
                    DataContainer.TestCasesRoot.ChangeCondition(index, coClone);
                }
            }
        }

        private static int CalculateRowIndex(ExecutedRoutedEventArgs e)
        {
            DataGrid dataGrid = e.Source as DataGrid;
            DependencyObject dep = e.OriginalSource as DependencyObject;
            DataGridRow dataGridRow = WpfTools.SearchForParent(dep, typeof(DataGridRow), false) as DataGridRow;
            if (dataGridRow != null && dataGrid != null)
            {
                int index = dataGrid.ItemContainerGenerator.IndexFromContainer(dataGridRow);
                return index;
            }
            return -1;
        }

        private static int CalculateColumnIndex(RoutedEventArgs e, bool trace=false)
        {
            DependencyObject dep = e.OriginalSource as DependencyObject;
            DataGridCell dataGridCell = WpfTools.SearchForParent(dep, typeof(DataGridCell), trace) as DataGridCell;
            if (dataGridCell != null)
            {
                return dataGridCell.Column.DisplayIndex;
            }
            return -1;
        }


        private void EditCondition_OnCanExecute(object sender, CanExecuteRoutedEventArgs e)
        {
            ConditionObject condObject = GetGridCellControlDataContext(e.Source as DataGrid, e.OriginalSource as DependencyObject) as ConditionObject;
            if (condObject != null)
            {
                e.CanExecute = true;
            }
        }

        private void EditAction_Executed(object sender, ExecutedRoutedEventArgs e)
        {
            var index = CalculateRowIndex(e);
            if (index >= 0)
            {
                ActionObject original = ((ActionObject)DataContainer.TestCasesRoot.Actions[index]);
                ActionObject coClone = original.Clone();
                EditCondition wnd = new EditCondition(coClone);
                bool? result = wnd.ShowDialog();
                if (result.HasValue && result.Value)
                {
                    DataContainer.TestCasesRoot.ChangeAction(index, coClone);
                }
            }
        }

        private void EditAction_OnCanExecute(object sender, CanExecuteRoutedEventArgs e)
        {
            ActionObject actionObject = GetGridCellControlDataContext(e.Source as DataGrid, e.OriginalSource as DependencyObject) as ActionObject;
            if (actionObject != null)
            {
                e.CanExecute = true;
            }
        }

        private void Save_Executed(object sender, ExecutedRoutedEventArgs e)
        {
            SaveFileDialog dlg = new SaveFileDialog();
            dlg.Filter = "Decision Table Creator Files|*.dtc|All Files|*.*";
            var result = dlg.ShowDialog();
            if (result.HasValue && result.Value)
            {
                DataContainer.TestCasesRoot.Save(dlg.FileName);
            }
        }

        private void Save_OnCanExecute(object sender, CanExecuteRoutedEventArgs e)
        {
            e.CanExecute = true;
        }

        private void Open_Executed(object sender, ExecutedRoutedEventArgs e)
        {
            OpenFileDialog dlg = new OpenFileDialog();
            dlg.Filter = "Decision Table Creator Files|*.dtc|All Files|*.*";
            var result = dlg.ShowDialog();
            if (result.HasValue && result.Value)
            {
                DataContainer.TestCasesRoot = TestCasesRoot.Load(dlg.FileName);
            }
        }

        private void NewDocument_OnCanExecute(object sender, CanExecuteRoutedEventArgs e)
        {
            e.CanExecute = true;
        }

        private void NewDocument_Executed(object sender, ExecutedRoutedEventArgs e)
        {
            DataContainer.TestCasesRoot = new TestCasesRoot();
        }


        private void Open_OnCanExecute(object sender, CanExecuteRoutedEventArgs e)
        {
            e.CanExecute = true;
        }

        private void AppendAction_Executed(object sender, ExecutedRoutedEventArgs e)
        {
            DataContainer.TestCasesRoot.AppendAction();
        }

        private void AppendAction_OnCanExecute(object sender, CanExecuteRoutedEventArgs e)
        {
            e.CanExecute = true;
        }

        private void AppendCondition_Executed(object sender, ExecutedRoutedEventArgs e)
        {
            DataContainer.TestCasesRoot.AppendCondition();
        }

        private void AppendCondition_OnCanExecute(object sender, CanExecuteRoutedEventArgs e)
        {
            e.CanExecute = true;
        }


        object GetGridCellControlDataContext(DataGrid dataGrid, DependencyObject originalSource, bool trace = false)
        {
            if (dataGrid != null)
            {
                if (originalSource != null)
                {
                    if (trace) { Debug.Write("SearchForParent "); }
                    var parent = WpfTools.SearchForParent(originalSource, typeof(GridCellControl), trace);
                    if (trace) { Debug.WriteLine(""); }
                    if (parent != null)
                    {
                        return ((GridCellControl)parent).DataContext;
                    }
                }
            }
            return null;
        }

    }
}
